nelmio_api_doc:
  documentation:
    servers:
      - url : /
    paths:
      '/':
        get:
          tags:
            - Liste des Réservations
          summary: 'Liste des réservations par jour'
          description: 'Liste des réservations par jour'
          operationId: getAllReservations
          parameters:
            - name: dateStart
              in: query
              description: 'Starting date au format YYYY-MM-DD'
              required: false
              schema:
                type: string
            - name: dateEnd
              in: query
              description: 'Ending date au format YYYY-MM-DD'
              required: false
              schema:
                type: string
          responses:
            '200':
              description: 'Recupération de la liste des réservations par jour'
            '400':
              description: 'Mauvais paramètres'
      '/add':
        post:
          tags:
            - Ajout d'une réservation
          summary: 'Ajouter une nouvelle réservation'
          description: 'Ajouter une nouvelle réservation'
          operationId: add
          requestBody:
            description: A JSON object containing pet information
            content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Reservation"
          responses:
            '200':
              description: 'Reservation ajouté au format JSON'
            '400':
              description: 'Mauvais paramètres'
      '/delete/{id}':
        delete:
          tags:
            - Suppression d'une réservation
          summary: 'Delete a reservation'
          description: 'Delete a unique reservation'
          operationId: delete
          parameters:
            -
              name: id
              in: path
              description: 'Unique Id'
              required: true
              schema:
                type: integer
          responses:
            '200':
              description: 'Reservation supprimé au format JSON'
    components:
      schemas:
        Reservation:
          title: 'Réservation'
          properties:
            date:
              type: date
            foodtruck:
              $ref: "#/components/schemas/Foodtruck"
            placement:
              $ref: "#/components/schemas/Placement"
        Foodtruck:
          title: 'Foodtruck'
          properties:
            id:
              type: string
        Placement:
          title: 'Placement'
          properties:
            id:
              type: int
      type: object

  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
